jQuery.fn.outerHTML=function(b){return b?this.before(b).remove():jQuery("<p>").append(this.eq(0).clone()).html()};String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};String.prototype.ltrim=function(){return this.replace(/^\s+/,"")};String.prototype.rtrim=function(){return this.replace(/\s+$/,"")};printObject=function(b){var a="",f;for(f in b)a+=f+": "+b[f]+"<br/>";return a};inArray=function(b,a){for(var f=!1,g=0;g<a.length;g++)a[g]==b&&(f=!0);return f};
cleanUsername=function(b){return b.replace("#!/","").replace("@","").replace("#","").replace(">","").ltrim().rtrim().toLowerCase()};addCommas=function(b){x=(b+"").split(".");x1=x[0];x2=1<x.length?"."+x[1]:"";for(b=/(\d+)(\d{3})/;b.test(x1);)x1=x1.replace(b,"$1,$2");return x1+x2};
var regUrls=/[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&//=]*)?/gi,regEmails=/[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9][a-z0-9-]*[a-z0-9]/gi,regTwitters=/(^|\s|>)@(\w+)/g;getLinks=function(b){return b=b.replace(/(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,"<a href='$1' target='_blank'>$1</a>")};var loggedUser=$("tr:eq(0)").find($('a[href^="user?"]')).attr("href");
void 0!=loggedUser&&(loggedUser=loggedUser.replace("user?id=",""));var forbiddenWebsites="twitter.com facebook.com about.me linkedin.com github.com foursquare.com klout.com quora.com @ gmail.com".split(" ");
displayProfile=function(b){var a="";void 0!=b.names[0]&&(a+="<div class='hackerfaceEntry'><div style='display:table;width:100%;'>",a+="<div style='width:50px;height:50px;float:left;'>",a=b.pictures[0]?a+("<img style='width:50px;height:50px;border-radius:2px;' src='"+b.pictures[0]+"'>"):a+"<img style='width:50px;height:50px;border-radius:2px;' src='https://raw.github.com/Gwendall/hackerface/gh-pages/stache.png'>",a+="</div>",a+="<div style='margin-left:10px;float:left;'>",void 0!=b.names[0]&&(a+="<div style='font-weight:bold;'>"+
b.names[0]+"</div>"),void 0!=b.locations[0]&&(a+="<div style='margin-top:5px;font-size:11px;'>"+b.locations[0]+"</div>"),a+="</div>",a+="</div>",a+="</div>");a+="<div class='hackerfaceEntry'>";a+="<div style='display:table;width:100%;'>";a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/hackernews.png' class='hackerfaceIcon'>";a+="<a class='hackerfaceUsername' href='http://news.ycombinator.com/user?id="+b.user+"' target='_blank'>"+b.user+"</a>";a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>";
a+="<span>"+addCommas(b.karma)+" karma</span>";b.user==loggedUser&&(a+="<span style=''> (nice job, "+loggedUser+"!)</span>");a+="</div>";b.about&&(a+="<div class='hackerfaceSubentry'>",a+=getLinks(b.about),a+="</div>");a+="</div>";b.twitters.length&&void 0!=b.twitters[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div style='display:table;width:100%;'>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/twitter.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://twitter.com/"+
b.twitters[0]+"' target='_blank'>@"+b.twitters[0]+"</a>",void 0!=b.twitterDetails[0]&&(void 0!==b.twitterDetails[0].followers_count&&(a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",a+="<span>"+addCommas(b.twitterDetails[0].followers_count)+" followers</span>"),void 0!==b.twitterDetails[0].friends_count&&(a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",a+="<span>"+addCommas(b.twitterDetails[0].friends_count)+" following</span>")),a+="</div>",
void 0!=b.twitterDetails[0]&&void 0!=b.twitterDetails[0].description&&(a+="<div class='hackerfaceSubentry'>",a+=getLinks(b.twitterDetails[0].description),a+="</div>"),a+="</div>");b.klouts.length&&void 0!=b.klouts[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/klout.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://klout.com/"+b.klouts[0]+"' target='_blank'>@"+b.klouts[0]+"</a>",a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",
a+="<span>"+Math.round(b.kloutDetails.score)+" klouts</span>",a+="</div>",a+="</div>");b.githubs.length&&void 0!=b.githubDetails[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/github.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://github.com/"+b.githubs[0]+"' target='_blank'>"+b.githubDetails[0].name+"</a>",void 0!==b.githubDetails[0].public_repos&&(a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",
a+="<span>"+addCommas(b.githubDetails[0].public_repos)+" repos</span>"),void 0!==b.githubDetails[0].public_gists&&(a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",a+="<span>"+addCommas(b.githubDetails[0].public_gists)+" gists</span>"),a+="</div>",a+="</div>");b.linkedins.length&&void 0!=b.linkedins[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/linkedin.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://linkedin.com/in/"+
b.linkedins[0]+"' target='_blank'>"+b.linkedins[0]+"</a>",a+="</div>",a+="</div>");b.angels.length&&void 0!=b.angels[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/angel.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://angel.co/"+b.angels[0]+"' target='_blank'>"+b.angels[0]+"</a>",a+="</div>",a+="</div>");b.facebooks.length&&void 0!=b.facebookDetails[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div style='display:table;width:100%;'>",
a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/facebook.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://facebook.com/"+b.facebooks[0]+"' target='_blank'>"+b.facebookDetails[0].name+"</a>",a+="</div>",a+="</div>");b.googlepluses.length&&void 0!=b.googleplusDetails[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/googleplus.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='https://plus.google.com/"+
b.googlepluses[0]+"' target='_blank'>"+b.googleplusDetails[0].displayName+"</a>",a+="</div>",a+="</div>");b.foursquares.length&&void 0!=b.foursquareDetails[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/foursquare.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://foursquare.com/user/"+b.foursquares[0]+"' target='_blank'>"+b.foursquareDetails[0].firstName+" "+b.foursquareDetails[0].lastName+"</a>",
a+="</div>",a+="</div>");b.quoras.length&&void 0!=b.quoras[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/quora.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://quora.com/"+b.quoras[0]+"' target='_blank'>"+b.quoras[0]+"</a>",a+="</div>",a+="</div>");b.aboutmes.length&&void 0!=b.aboutmes[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/aboutme.png' class='hackerfaceIcon'>",
a+="<a class='hackerfaceUsername' href='http://about.me/"+b.aboutmes[0]+"' target='_blank'>"+b.aboutmes[0]+"</a>",a+="</div>",a+="</div>");if(b.emails.length&&void 0!=b.emails[0])for(i in b.emails)void 0!=b.emails[i]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/mail.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='mailto:"+b.emails[i]+"' target='_blank'>"+b.emails[i]+"</a>",a+="</div>",a+="</div>");var f=
[];for(i in b.websitesBase){var g=0;for(j in forbiddenWebsites)-1!=b.websitesBase[i].toLowerCase().indexOf(forbiddenWebsites[j])&&(g=1);for(k in f)-1!=b.websitesBase[i].indexOf(f[k])&&(g=1);g||f.push(b.websitesBase[i])}if(f.length&&void 0!=f[0]){a+="<div class='hackerfaceEntry'>Website";1<f.length&&(a+="s");a+=": ";for(i in f)a+="<a href='"+f[i]+"' target='_blank'>"+f[i]+"</a>",i<f.length-1&&(a+=", ");a+="</div>"}return a};
$(document).ready(function(){function b(){f=$(window).height()-$("#boxHackerfaceInner").offset().top+$(window).scrollTop();$("#boxHackerfaceInner").css("max-height",f+"px")}if($('a[href^="user?"]').length){var a="<div id='boxHackerface'";0==localStorage.shown&&(a+=" class='hackerboxHidden'");a+="><div class='hackerfaceHide hackerfaceCross'>x</div>";a+="<div id='boxHackerfaceInner'>";a+="<div class='hackerfaceEntry'>";a+="<div>"+$('a[href^="user?"]').length+" users found in this page.</div>";a+="<div style='margin-top:3px;'>Hover over a username to get more details.</div>";
a+="</div>";a+="</div>";a+="</div>";$("tbody:eq(0)").css({position:"relative"}).prepend(a);a="<td style='text-align:right;color:black;cursor:pointer;' id='hackerfaceHide' class='hackerfaceHide'>";a=1==localStorage.shown?a+"hide hackerface":a+"show hackerface";$("tr:eq(1) td:eq(1)").after(a+"</td>")}$(".hackerfaceHide").live("click",function(){$("#boxHackerface").toggleClass("hackerboxHidden");$("#boxHackerface").hasClass("hackerboxHidden")?($("#hackerfaceHide").html("show hackerface"),localStorage.shown=
0):($("#hackerfaceHide").html("hide hackerface"),localStorage.shown=1)});var f;b();window.onresize=function(){b()};var g=Math.max($("tr:eq(0)").offset().top+$("tr:eq(0)").height()-$(window).scrollTop(),0),l=g+7;$("#boxHackerfaceInner").css("top",g+"px");$(".hackerfaceCross").css("top",l+"px");$(window).scroll(function(){g=Math.max($("tr:eq(0)").offset().top+$("tr:eq(0)").height()-$(window).scrollTop(),0);l=g+7;$("#boxHackerfaceInner").css("top",g+"px");$(".hackerfaceCross").css("top",l+"px")});var e=
0,n=["share","widgets.js","intent","replies","statuses","!","search","import","media",void 0];parseTwitter=function(a){$.ajax({accepts:"text/html",url:"https://api.twitter.com/1/users/show.json?include_entities=true&screen_name="+a}).success(function(b){d.twitterDetails.push(b);d.locations.push(b.location);d.bios.push(b.description);d.names.push(b.name);$("#boxHackerfaceInner").html(displayProfile(d));$.ajax({dataType:"json",url:"https://api.foursquare.com/v2/users/search?oauth_token=VYAAZLEWQT5QU4YN2YOF55NFMQ1WZNHGBAIYHPSCA00KBA5E&v=20120620&twitter="+
a}).success(function(a){a=a.response.results[0];void 0!==a&&(d.foursquares.push(a.id),d.foursquareDetails.push(a),d.locations.push(a.homeCity),d.bios.push(a.bio),d.names.push(a.firstName+" "+a.lastName),d.emails.push(a.contact.email),$("#boxHackerfaceInner").html(displayProfile(d)),void 0!==a.contact.facebook&&(d.facebooks.push(a.contact.facebook),$.ajax({dataType:"json",url:"http://graph.facebook.com/"+a.contact.facebook}).success(function(a){d.names.push(a.name);d.facebookDetails.push(a);$("#boxHackerfaceInner").html(displayProfile(d))})))});
$.ajax({dataType:"json",url:"http://api.klout.com/v2/identity.json/twitter?key=t3zd36eerj6h2scqea86qex6&screenName="+a}).success(function(b){void 0!=b&&$.ajax({dataType:"json",url:"http://api.klout.com/v2/user.json/"+b.id+"/score?key=t3zd36eerj6h2scqea86qex6"}).success(function(b){d.klouts.push(a);d.kloutDetails=b;$("#boxHackerfaceInner").html(displayProfile(d))})})}).error(function(){$("#boxHackerfaceInner").html(displayProfile(d))})};extractContacts=function(a,b){if(null!==a.match(regUrls))for(e in a.match(regUrls)){var c=
a.match(regUrls)[e];-1==c.indexOf("http://news.ycombinator.com")&&(-1==c.indexOf("http://ycombinator.com")&&!inArray(c,b.websites)&&-1==c.indexOf("@"))&&("http"!=c.substring(0,4)&&(c="http://"+c),b.websites.push(c))}if(null!==a.match(regEmails))for(e in a.match(regEmails))c=a.match(regEmails)[e],!inArray(c,b.emails)&&("0"!=c&&""!=c&&"-"!=c&&-1==c.indexOf("/"))&&b.emails.push(c);if(null!==a.match(regTwitters))for(e=0;1>e;e++)c=cleanUsername(a.match(regTwitters)[e]),!inArray(c,b.twitters)&&(!inArray(c,
n)&&""!=c)&&(b.twitters.push(c),b.pictures.push("https://api.twitter.com/1/users/profile_image?screen_name="+c+"&size=normal"),parseTwitter(c));if(b.websites.length)for(e in b.websites)-1!=b.websites[e].indexOf("twitter.com")?(c=cleanUsername(b.websites[e]),void 0!==c&&(c=c.split("twitter.com/")[1],void 0!==c&&(c=c.replace("/#!",""),void 0!==c&&(c=c.split("/")[0],void 0!==c&&(c=c.split("?")[0])))),!inArray(c,b.twitters)&&(!inArray(c,n)&&""!=c&&0==b.twitters.length)&&(b.twitters.push(c),b.pictures.push("https://api.twitter.com/1/users/profile_image?screen_name="+
c+"&size=normal"),parseTwitter(c))):-1!=b.websites[e].indexOf("/github.com")||-1!=b.websites[e].indexOf("www.github.com")?(c=cleanUsername(b.websites[e]),void 0!==c&&(c=c.split("github.com/")[1],void 0!==c&&(c=c.split("/")[0])),!inArray(c,b.githubs)&&""!=c&&(b.githubs.push(c),$.ajax({dataType:"json",url:"https://api.github.com/users/"+c}).success(function(a){b.githubDetails.push(a);b.locations.push(a.location);b.bios.push(a.bio);b.names.push(a.name);b.pictures.push(a.avatar_url);b.websites.push(a.blog);
inArray(a.email,b.emails)||b.emails.push(a.email)}))):-1!=b.websites[e].indexOf("linkedin.com/in")?(c=cleanUsername(b.websites[e]),void 0!==c&&(c=c.split("linkedin.com/in/")[1],void 0!==c&&(c=c.split("/")[0])),inArray(c,b.linkedins)||b.linkedins.push(c)):-1!=b.websites[e].indexOf("angel.co")?(c=cleanUsername(b.websites[e]),void 0!==c&&(c=c.split("angel.co/")[1],void 0!==c&&(c=c.split("/")[0])),inArray(c,b.angels)||b.angels.push(c)):-1!=b.websites[e].indexOf("plus.google.com")?(c=cleanUsername(b.websites[e]),
void 0!==c&&(c=c.split("plus.google.com/")[1],void 0!==c&&(c=c.split("/")[0])),inArray(c,b.googlepluses)||(b.googlepluses.push(c),$.ajax({dataType:"json",url:"https://www.googleapis.com/plus/v1/people/"+c+"?key=AIzaSyCVbyyMn-QR7Q4WGtq03yQVBs_KksoxAiU"}).success(function(a){b.googleplusDetails.push(a);b.names.push(a.displayName);b.pictures.push(a.image.url);for(j in a.placesLived)b.locations.push(a.placesLived[j].value)}))):-1!=b.websites[e].indexOf("about.me")?(c=cleanUsername(b.websites[e]),void 0!==
c&&(c=c.split("about.me/")[1],void 0!==c&&(c=c.split("/")[0])),inArray(c,b.aboutmes)||b.aboutmes.push(c)):-1!=b.websites[e].indexOf("quora.com")&&(c=cleanUsername(b.websites[e]),void 0!==c&&(c=c.split("quora.com/")[1],void 0!==c&&(c=c.split("/")[0])),inArray(c,b.quoras)||b.quoras.push(c));return b};var m=[];$.ajaxSetup({beforeSend:function(a){m.push(a)}});abortAllAjaxCalls=function(){for(e in m)m[e].abort()};var h,d={};$('a[href^="user?"]').live("mouseenter",function(){abortAllAjaxCalls();d={};d.user=
$(this).attr("href").replace("user?id=","");null!=h&&(clearTimeout(h),h=null);h=setTimeout(function(){d.user==loggedUser?$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Searching for you, "+d.user+"...</div>"):$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Searching about "+d.user+"...</div>");d.request="http://news.ycombinator.com/user?id="+d.user;d.websites=[];d.websitesBase=[];d.emails=[];d.twitters=[];d.twitterDetails=[];d.githubs=[];d.githubDetails=[];d.klouts=[];d.kloutDetails=
{};d.facebooks=[];d.facebookDetails=[];d.foursquares=[];d.foursquareDetails=[];d.googlepluses=[];d.googleplusDetails=[];d.angels=[];d.angelDetails={};d.aboutmes=[];d.aboutmeDetails={};d.quoras=[];d.quoraDetails={};d.linkedins=[];d.pictures=[];d.locations=[];d.bios=[];d.names=[];$.ajax({accepts:"text/html",url:d.request}).success(function(a){$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Found HN profile...</div>");"pg"==d.user?d.about="@paulg":(d.about=$(a).find("tbody:eq(2)").find("td:eq(9)")[0].innerHTML,
d.about=d.about.replace(" [dot] ",".").replace("[dot]",".").replace(" DOT ","."),d.about=d.about.replace(" [at] ","@").replace("[at]","@").replace(" AT ","@"),d.user==loggedUser&&(d.about=d.about.split('<textarea cols="60" rows="7" wrap="virtual" name="about">')[1].split("</textarea")[0]));d.karma=$(a).find("tbody:eq(2)").find("td:eq(5)")[0].innerHTML;if(null!==d.about.match(regUrls))for(e in d.about.match(regUrls))a=d.about.match(regUrls)[e],-1==a.indexOf("http://news.ycombinator.com")&&(-1==a.indexOf("http://ycombinator.com")&&
!inArray(a,d.websitesBase))&&("http"!=a.substring(0,4)&&(a="http://"+a),d.websitesBase.push(a));if(null!==d.about)if(d.bios.push(d.about),extractContacts(d.about,d),d.websites.length)for(e in d.websites)void 0!==d.websites[e]&&-1==d.websites[e].indexOf("gmail.com")?($("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Extracting "+d.websites[e]+"...</div>"),$.ajax({accepts:"text/html",url:d.websites[e]}).success(function(a){$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Extracted "+
d.websites[e]+"</div>");null!==a?(extractContacts(a,d),e==d.websites.length-1&&$("#boxHackerfaceInner").html(displayProfile(d))):$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Nothing found in "+d.websites[e]+"</div>")}).error(function(){$("#boxHackerfaceInner").html(displayProfile(d))})):$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>"+d.websites[e]+" undefined</div>");else $("#boxHackerfaceInner").html(displayProfile(d));else $("#boxHackerfaceInner").html(displayProfile(d))})},
1E3)})});