jQuery.fn.outerHTML=function(c){return c?this.before(c).remove():jQuery("<p>").append(this.eq(0).clone()).html()};String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};String.prototype.ltrim=function(){return this.replace(/^\s+/,"")};String.prototype.rtrim=function(){return this.replace(/\s+$/,"")};pushAwesome=function(c,a){inArray(c,a)||a.push(c);return!0};printObject=function(c){var a="",e;for(e in c)a+=e+": "+c[e]+"<br/>";return a};
inArray=function(c,a){for(var e=!1,f=0;f<a.length;f++)a[f]==c&&(e=!0);return e};cleanUsername=function(c){return c.replace("#!/","").replace("@","").replace("#","").replace(">","").ltrim().rtrim().toLowerCase()};addCommas=function(c){x=(c+"").split(".");x1=x[0];x2=1<x.length?"."+x[1]:"";for(c=/(\d+)(\d{3})/;c.test(x1);)x1=x1.replace(c,"$1,$2");return x1+x2};
var regUrls=/[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&//=]*)?/gi,regEmails=/[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9][a-z0-9-]*[a-z0-9]/gi,regTwitters=/(^|\s|>)@(\w+)/g;getLinks=function(c){return c=c.replace(/(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,"<a href='$1' target='_blank'>$1</a>")};var loggedUser=$("tr:eq(0)").find($('a[href^="user?"]')).attr("href");
void 0!=loggedUser&&(loggedUser=loggedUser.replace("user?id=",""));var forbiddenWebsites="twitter.com facebook.com about.me linkedin.com github.com foursquare.com klout.com quora.com @ gmail.com".split(" ");
displayProfile=function(c){var a="";void 0!==c.errors&&(a+="<div class='hackerfaceEntry hackerfaceError'><img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/alert.png' class='hackerfaceIcon'>",a+="<span class='hackerfaceUsername'>"+c.errors+"</a>",a+="</div>");void 0!=c.names[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div style='display:table;width:100%;'>",a+="<div style='width:50px;height:50px;float:left;'>",a=c.pictures[0]?a+("<img style='width:50px;height:50px;border-radius:2px;' src='"+
c.pictures[0]+"'>"):a+"<img style='width:50px;height:50px;border-radius:2px;' src='https://raw.github.com/Gwendall/hackerface/gh-pages/stache.png'>",a+="</div>",a+="<div style='margin-left:10px;float:left;'>",void 0!=c.names[0]&&(a+="<div style='font-weight:bold;'>"+c.names[0]+"</div>"),void 0!=c.locations[0]&&(a+="<div style='margin-top:5px;font-size:11px;'>"+c.locations[0]+"</div>"),a+="</div>",a+="</div>",a+="</div>");a+="<div class='hackerfaceEntry'>";a+="<div style='display:table;width:100%;'>";
a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/hackernews.png' class='hackerfaceIcon'>";a+="<a class='hackerfaceUsername' href='http://news.ycombinator.com/user?id="+c.user+"' target='_blank'>"+c.user+"</a>";a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>";a+="<span>"+addCommas(c.karma)+" karma</span>";c.user==loggedUser&&(a+="<span style=''> (nice job, "+loggedUser+"!)</span>");a+="</div>";c.about&&(a+="<div class='hackerfaceSubentry'>",a+=getLinks(c.about),
a+="</div>");a+="</div>";c.twitters.length&&void 0!=c.twitters[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div style='display:table;width:100%;'>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/twitter.png' class='hackerfaceIcon'>",a+="<div class='hackerfaceUsername'>",a+="<a href='http://twitter.com/"+c.twitters[0]+"' target='_blank'>@"+c.twitters[0]+"</a>",void 0!=c.twitterDetails[0]&&(void 0!==c.twitterDetails[0].followers_count&&(a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",
a+="<span>"+addCommas(c.twitterDetails[0].followers_count)+" followers</span>"),void 0!==c.twitterDetails[0].friends_count&&(a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",a+="<span>"+addCommas(c.twitterDetails[0].friends_count)+" following</span>")),a+="</div>",a+="</div>",void 0!=c.twitterDetails[0]&&void 0!=c.twitterDetails[0].description&&(a+="<div class='hackerfaceSubentry'>",a+=getLinks(c.twitterDetails[0].description),a+="</div>"),a+="</div>");c.klouts.length&&
void 0!=c.klouts[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/klout.png' class='hackerfaceIcon'>",a+="<div class='hackerfaceUsername'>",a+="<a href='http://klout.com/"+c.klouts[0]+"' target='_blank'>@"+c.klouts[0]+"</a>",a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",a+="<span>"+Math.round(c.kloutDetails.score)+" klouts</span>",a+="</div>",a+="</div>",a+="</div>");c.githubs.length&&(void 0!=
c.githubDetails[0]&&void 0!=c.githubDetails[0].name)&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/github.png' class='hackerfaceIcon'>",a+="<div class='hackerfaceUsername'>",a+="<a href='http://github.com/"+c.githubs[0]+"' target='_blank'>"+c.githubDetails[0].name+"</a>",void 0!==c.githubDetails[0].public_repos&&(a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",a+="<span>"+addCommas(c.githubDetails[0].public_repos)+
" repos</span>"),void 0!==c.githubDetails[0].public_gists&&(a+="<span style='margin-left:3px;margin-right:3px;color:gray;'>\u00b7</span>",a+="<span>"+addCommas(c.githubDetails[0].public_gists)+" gists</span>"),a+="</div>",a+="</div>",a+="</div>");c.linkedins.length&&void 0!=c.linkedins[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/linkedin.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://linkedin.com/in/"+
c.linkedins[0]+"' target='_blank'>"+c.linkedins[0]+"</a>",a+="</div>",a+="</div>");c.angels.length&&void 0!=c.angels[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/angel.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://angel.co/"+c.angels[0]+"' target='_blank'>"+c.angels[0]+"</a>",a+="</div>",a+="</div>");c.facebooks.length&&void 0!=c.facebookDetails[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div style='display:table;width:100%;'>",
a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/facebook.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://facebook.com/"+c.facebooks[0]+"' target='_blank'>"+c.facebookDetails[0].name+"</a>",a+="</div>",a+="</div>");c.googlepluses.length&&void 0!=c.googleplusDetails[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/googleplus.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='https://plus.google.com/"+
c.googlepluses[0]+"' target='_blank'>"+c.googleplusDetails[0].displayName+"</a>",a+="</div>",a+="</div>");c.foursquares.length&&void 0!=c.foursquareDetails[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/foursquare.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://foursquare.com/user/"+c.foursquares[0]+"' target='_blank'>"+c.foursquareDetails[0].fullName+"</a>",a+="</div>",a+="</div>");c.quoras.length&&
void 0!=c.quoras[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/quora.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='http://quora.com/"+c.quoras[0]+"' target='_blank'>"+c.quoras[0]+"</a>",a+="</div>",a+="</div>");c.aboutmes.length&&void 0!=c.aboutmes[0]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/aboutme.png' class='hackerfaceIcon'>",
a+="<a class='hackerfaceUsername' href='http://about.me/"+c.aboutmes[0]+"' target='_blank'>"+c.aboutmes[0]+"</a>",a+="</div>",a+="</div>");if(c.emails.length&&void 0!=c.emails[0])for(i in c.emails)void 0!=c.emails[i]&&""!=c.emails[i]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/mail.png' class='hackerfaceIcon'>",a+="<a class='hackerfaceUsername' href='mailto:"+c.emails[i]+"' target='_blank'>"+c.emails[i]+"</a>",a+="</div>",
a+="</div>");if(c.phones.length&&void 0!=c.phones[0])for(i in c.phones)void 0!=c.phones[i]&&(a+="<div class='hackerfaceEntry'>",a+="<div>",a+="<img src='https://raw.github.com/Gwendall/hackerface/gh-pages/icons/phone.png' class='hackerfaceIcon'>",a+="<span class='hackerfaceUsername'>"+c.phones[i]+"</span>",a+="</div>",a+="</div>");var e=[];for(i in c.websitesBase){var f=0;for(j in forbiddenWebsites)-1!=c.websitesBase[i].toLowerCase().indexOf(forbiddenWebsites[j])&&(f=1);for(k in e)-1!=c.websitesBase[i].indexOf(e[k])&&
(f=1);f||e.push(c.websitesBase[i])}if(e.length&&void 0!=e[0]){a+="<div class='hackerfaceEntry'>Website";1<e.length&&(a+="s");a+=": ";for(i in e)a+="<a href='"+e[i]+"' target='_blank'>"+e[i]+"</a>",i<e.length-1&&(a+=", ");a+="</div>"}return a};
$(document).ready(function(){function c(){e=$(window).height()-$("#boxHackerfaceInner").offset().top+$(window).scrollTop();$("#boxHackerfaceInner").css("max-height",e+"px")}if($('a[href^="user?"]').length){var a="<div id='boxHackerface'";0==localStorage.shown&&(a+=" class='hackerboxHidden'");a+="><div class='hackerfaceHide hackerfaceCross'>x</div>";a+="<div id='boxHackerfaceInner'>";a+="<div class='hackerfaceEntry'>";a+="<div>";a+=$('a[href^="user?"]').length+" user";1<$('a[href^="user?"]').length&&
(a+="s");a+=" found in this page.";a+="</div>";a=1==$('a[href^="user?"]').length?a+"<div style='margin-top:3px;'>Loading her details...</div>":a+"<div style='margin-top:3px;'>Hover over a username to get more details.</div>";a+="</div>";a+="</div>";a+="</div>";$("tbody:eq(0)").css({position:"relative"}).prepend(a);a="<td style='text-align:right;color:black;cursor:pointer;' id='hackerfaceHide' class='hackerfaceHide'>";a=1==localStorage.shown?a+"hide hackerface":a+"show hackerface";$("tr:eq(1) td:eq(1)").after(a+
"</td>")}$(".hackerfaceHide").live("click",function(){$("#boxHackerface").toggleClass("hackerboxHidden");$("#boxHackerface").hasClass("hackerboxHidden")?($("#hackerfaceHide").html("show hackerface"),localStorage.shown=0):($("#hackerfaceHide").html("hide hackerface"),localStorage.shown=1)});var e;c();window.onresize=function(){c()};var f=Math.max($("tr:eq(0)").offset().top+$("tr:eq(0)").height()-$(window).scrollTop(),0),m=f+7;$("#boxHackerfaceInner").css("top",f+"px");$(".hackerfaceCross").css("top",
m+"px");$(window).scroll(function(){f=Math.max($("tr:eq(0)").offset().top+$("tr:eq(0)").height()-$(window).scrollTop(),0);m=f+7;$("#boxHackerfaceInner").css("top",f+"px");$(".hackerfaceCross").css("top",m+"px")});var d=0,p=["share","widgets.js","intent","replies","statuses","!","search","import","media",void 0];getFacebook=function(a){$.ajax({dataType:"json",url:"http://graph.facebook.com/"+a}).success(function(c){b.names.push(c.name);b.facebooks.push(a);b.facebookDetails.push(c);searchFoursquare("facebook",
c.id);$("#boxHackerfaceInner").html(displayProfile(b))})};searchFoursquare=function(a,c){var g;"twitter"==a&&(g="https://api.foursquare.com/v2/users/search?oauth_token=VYAAZLEWQT5QU4YN2YOF55NFMQ1WZNHGBAIYHPSCA00KBA5E&v=20120620&twitter="+c);"facebook"==a&&(g="https://api.foursquare.com/v2/users/search?oauth_token=VYAAZLEWQT5QU4YN2YOF55NFMQ1WZNHGBAIYHPSCA00KBA5E&v=20120620&fbid="+c);"email"==a&&(g="https://api.foursquare.com/v2/users/search?oauth_token=VYAAZLEWQT5QU4YN2YOF55NFMQ1WZNHGBAIYHPSCA00KBA5E&v=20120620&email="+
c);$.ajax({dataType:"json",url:g}).success(function(c){c=c.response.results[0];void 0!==c&&(b.foursquares.push(c.id),c.fullName="",void 0!=c.firstName&&(c.fullName+=c.firstName+" "),void 0!=c.lastName&&"undefined"!=c.lastName&&(c.fullName+=c.lastName),b.foursquareDetails.push(c),b.bios.push(c.bio),pushAwesome(c.fullName,b.names),pushAwesome(c.homeCity,b.locations),pushAwesome(c.contact.email,b.emails),pushAwesome(c.contact.phone,b.phones),$("#boxHackerfaceInner").html(displayProfile(b)),"facebook"!=
a&&void 0!==c.contact.facebook&&getFacebook(c.contact.facebook),"twitter"!=a&&void 0!==c.contact.twitter&&getTwitter(c.contact.twitter))}).error(function(){$("#boxHackerfaceInner").html(displayProfile(b))})};searchKlout=function(a){$.ajax({dataType:"json",url:"http://api.klout.com/v2/identity.json/twitter?key=t3zd36eerj6h2scqea86qex6&screenName="+a}).success(function(c){void 0!=c&&$.ajax({dataType:"json",url:"http://api.klout.com/v2/user.json/"+c.id+"/score?key=t3zd36eerj6h2scqea86qex6"}).success(function(c){b.klouts.push(a);
b.kloutDetails=c;$("#boxHackerfaceInner").html(displayProfile(b))})})};getTwitter=function(a){pushAwesome(a,b.twitters);pushAwesome("https://api.twitter.com/1/users/profile_image?screen_name="+a+"&size=normal",b.pictures);$.ajax({accepts:"text/html",url:"https://api.twitter.com/1/users/show.json?include_entities=true&screen_name="+a}).success(function(a){b.twitterDetails.push(a);b.locations.push(a.location);b.bios.push(a.description);b.names.push(a.name);$("#boxHackerfaceInner").html(displayProfile(b))}).error(function(){b.errors=
"Twitter API limit reached for this hour.";$("#boxHackerfaceInner").html(displayProfile(b))})};getGoogleplus=function(a){b.googlepluses.push(a);$.ajax({dataType:"json",url:"https://www.googleapis.com/plus/v1/people/"+a+"?key=AIzaSyCVbyyMn-QR7Q4WGtq03yQVBs_KksoxAiU"}).success(function(a){b.googleplusDetails.push(a);b.names.push(a.displayName);b.pictures.push(a.image.url);for(j in a.placesLived)b.locations.push(a.placesLived[j].value)})};getGithub=function(a){b.githubs.push(a);$.ajax({dataType:"json",
url:"https://api.github.com/users/"+a}).success(function(a){b.githubDetails.push(a);b.locations.push(a.location);b.bios.push(a.bio);b.names.push(a.name);b.pictures.push(a.avatar_url);b.websites.push(a.blog);inArray(a.email,b.emails)||b.emails.push(a.email)})};extractContacts=function(a,c){if(null!==a.match(regUrls))for(d in a.match(regUrls)){var b=a.match(regUrls)[d];-1==b.indexOf("http://news.ycombinator.com")&&(-1==b.indexOf("http://ycombinator.com")&&!inArray(b,c.websites)&&-1==b.indexOf("@"))&&
("http"!=b.substring(0,4)&&(b="http://"+b),c.websites.push(b))}if(null!==a.match(regEmails))for(d in a.match(regEmails))b=a.match(regEmails)[d],!inArray(b,c.emails)&&("0"!=b&&""!=b&&"-"!=b&&-1==b.indexOf("/")&&-1==b.indexOf("%"))&&(c.emails.push(b),searchFoursquare("email",b));if(null!==a.match(regTwitters))for(d=0;1>d;d++)b=cleanUsername(a.match(regTwitters)[d]),!inArray(b,c.twitters)&&(!inArray(b,p)&&""!=b)&&(getTwitter(b),searchFoursquare("twitter",b),searchKlout(b));if(c.websites.length)for(d in c.websites)-1!=
c.websites[d].indexOf("twitter.com")?(b=cleanUsername(c.websites[d]),void 0!==b&&(b=b.split("twitter.com/")[1],void 0!==b&&(b=b.replace("/#!",""),void 0!==b&&(b=b.split("/")[0],void 0!==b&&(b=b.split("?")[0])))),!inArray(b,c.twitters)&&(!inArray(b,p)&&""!=b&&0==c.twitters.length)&&(getTwitter(b),searchFoursquare("twitter",b),searchKlout(b))):-1!=c.websites[d].indexOf("/github.com")||-1!=c.websites[d].indexOf("www.github.com")?(b=cleanUsername(c.websites[d]),void 0!==b&&(b=b.split("github.com/")[1],
void 0!==b&&(b=b.split("/")[0])),!inArray(b,c.githubs)&&""!=b&&getGithub(b)):-1!=c.websites[d].indexOf("linkedin.com/in")?(b=cleanUsername(c.websites[d]),void 0!==b&&(b=b.split("linkedin.com/in/")[1],void 0!==b&&(b=b.split("/")[0])),inArray(b,c.linkedins)||c.linkedins.push(b)):-1!=c.websites[d].indexOf("angel.co")?(b=cleanUsername(c.websites[d]),void 0!==b&&(b=b.split("angel.co/")[1],void 0!==b&&(b=b.split("/")[0])),inArray(b,c.angels)||c.angels.push(b)):-1!=c.websites[d].indexOf("plus.google.com")?
(b=cleanUsername(c.websites[d]),void 0!==b&&(b=b.split("plus.google.com/")[1],void 0!==b&&(b=b.split("/")[0])),inArray(b,c.googlepluses)||getGoogleplus(b)):-1!=c.websites[d].indexOf("about.me")?(b=cleanUsername(c.websites[d]),void 0!==b&&(b=b.split("about.me/")[1],void 0!==b&&(b=b.split("/")[0])),inArray(b,c.aboutmes)||c.aboutmes.push(b)):-1!=c.websites[d].indexOf("quora.com")&&(b=cleanUsername(c.websites[d]),void 0!==b&&(b=b.split("quora.com/")[1],void 0!==b&&(b=b.split("/")[0])),inArray(b,c.quoras)||
c.quoras.push(b));return c};var n=[];$.ajaxSetup({beforeSend:function(a){n.push(a)}});abortAllAjaxCalls=function(){for(d in n)n[d].abort()};startShit=function(a){abortAllAjaxCalls();b={};b.user=a;null!=h&&(clearTimeout(h),h=null);h=setTimeout(function(){b.user==loggedUser?$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Searching for you, "+b.user+"...</div>"):$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Searching about "+b.user+"...</div>");b.request="http://news.ycombinator.com/user?id="+
b.user;b.websites=[];b.websitesBase=[];b.emails=[];b.twitters=[];b.twitterDetails=[];b.githubs=[];b.githubDetails=[];b.klouts=[];b.kloutDetails={};b.facebooks=[];b.facebookDetails=[];b.foursquares=[];b.foursquareDetails=[];b.googlepluses=[];b.googleplusDetails=[];b.angels=[];b.angelDetails={};b.aboutmes=[];b.aboutmeDetails={};b.quoras=[];b.quoraDetails={};b.linkedins=[];b.pictures=[];b.locations=[];b.bios=[];b.names=[];b.phones=[];$.ajax({accepts:"text/html",url:b.request}).success(function(a){$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Found HN profile...</div>");
"pg"==b.user?b.about="@paulg":(b.about=$(a).find("tbody:eq(2)").find("td:eq(9)")[0].innerHTML,b.about=b.about.replace(" [dot] ",".").replace("[dot]",".").replace(" DOT ","."),b.about=b.about.replace(" [at] ","@").replace("[at]","@").replace(" AT ","@"),b.user==loggedUser&&(b.about=b.about.split('<textarea cols="60" rows="7" wrap="virtual" name="about">')[1].split("</textarea")[0]));b.karma=$(a).find("tbody:eq(2)").find("td:eq(5)")[0].innerHTML;if(null!==b.about.match(regUrls))for(d in b.about.match(regUrls))a=
b.about.match(regUrls)[d],-1==a.indexOf("http://news.ycombinator.com")&&(-1==a.indexOf("http://ycombinator.com")&&!inArray(a,b.websitesBase))&&("http"!=a.substring(0,4)&&(a="http://"+a),b.websitesBase.push(a));if(null!==b.about)if(b.bios.push(b.about),extractContacts(b.about,b),b.websites.length)for(d in b.websites)void 0!==b.websites[d]&&-1==b.websites[d].indexOf("gmail.com")?($("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Extracting "+b.websites[d]+"...</div>"),$.ajax({accepts:"text/html",
url:b.websites[d]}).success(function(a){$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Extracted "+b.websites[d]+"</div>");null!==a?(extractContacts(a,b),d==b.websites.length-1&&$("#boxHackerfaceInner").html(displayProfile(b))):$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>Nothing found in "+b.websites[d]+"</div>")}).error(function(){$("#boxHackerfaceInner").html(displayProfile(b))})):$("#boxHackerfaceInner").html("<div class='hackerfaceEntry'>"+b.websites[d]+" undefined</div>");
else $("#boxHackerfaceInner").html(displayProfile(b));else $("#boxHackerfaceInner").html(displayProfile(b))})},1E3)};var h,b={},l;$('a[href^="user?"]').live("mouseenter",function(){l=$(this).attr("href").replace("user?id=","");startShit(l)});1==$('a[href^="user?"]').length&&(l=$('a[href^="user?"]:eq(0)').attr("href").replace("user?id=",""),startShit(l))});